<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Auth extends CI_Controller
{
    
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->library('form_validation');        
    }
    public function index(){
        $this->load->view('auth', array(), FALSE);
    }
    public function login(){
        $nik = $this->input->post('nik');
        $password = $this->input->post('password');
        
        $auth = $this->User_model->get_user_by_auth($nik,$password);
        if ($auth) {
            $data_session = array(
                'id' => $auth->id,
				'nama' => $auth->nama,
				'status' => $auth->status_id
				);
            $this->session->set_userdata('auth',$data_session);
            
            redirect('keluarga','refresh');
        }else{
            var_dump($auth);
            redirect('auth','refresh');
        }
    }
    public function logout(){
        $this->session->sess_destroy();
	    redirect('auth','refresh');
    }
    

}

/* End of file Jenis_pangan.php */
/* Location: ./application/controllers/Jenis_pangan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-15 10:06:14 */
/* http://harviacode.com */