<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Desa extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Desa_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('desa/desa_list');
    } 
    public function get_by_kecamatan($kec){
        echo json_encode($this->Desa_model->get_by_kecamatan($kec));
    }
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Desa_model->json();
    }

    public function read($id) 
    {
        $row = $this->Desa_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_desa' => $row->id_desa,
		'kec_id' => $row->kec_id,
		'nama_desa' => $row->nama_desa,
	    );
            $this->load->view('desa/desa_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('desa'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('desa/create_action'),
	    'id_desa' => set_value('id_desa'),
	    'kec_id' => set_value('kec_id'),
	    'nama_desa' => set_value('nama_desa'),
	);
        $this->load->view('desa/desa_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'kec_id' => $this->input->post('kec_id',TRUE),
		'nama_desa' => $this->input->post('nama_desa',TRUE),
	    );

            $this->Desa_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('desa'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Desa_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('desa/update_action'),
		'id_desa' => set_value('id_desa', $row->id_desa),
		'kec_id' => set_value('kec_id', $row->kec_id),
		'nama_desa' => set_value('nama_desa', $row->nama_desa),
	    );
            $this->load->view('desa/desa_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('desa'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_desa', TRUE));
        } else {
            $data = array(
		'kec_id' => $this->input->post('kec_id',TRUE),
		'nama_desa' => $this->input->post('nama_desa',TRUE),
	    );

            $this->Desa_model->update($this->input->post('id_desa', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('desa'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Desa_model->get_by_id($id);

        if ($row) {
            $this->Desa_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('desa'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('desa'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('kec_id', 'kec id', 'trim|required');
	$this->form_validation->set_rules('nama_desa', 'nama desa', 'trim|required');

	$this->form_validation->set_rules('id_desa', 'id_desa', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Desa.php */
/* Location: ./application/controllers/Desa.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-08 14:45:33 */
/* http://harviacode.com */