<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Survei_model extends CI_Model
{

    public $table = 'survei';
    public $id = 'survei.id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('survei.id,keluarga.kepala_keluarga,keluarga.penyuluh_id');
        $this->datatables->from('survei');
        //add this line for join
        $this->datatables->join('keluarga', 'survei.keluarga_id = keluarga.id');
        $this->datatables->add_column('action', anchor(site_url('survei/read/$1'),'Detail')." | ".anchor(site_url('survei/update/$1'),'Perbarui')." | ".anchor(site_url('survei/delete/$1'),'Hapus','onclick="javasciprt: return confirm(\'Apakah anda yakin ?\')"'), 'id');
        return $this->datatables->generate();
    }
    function json_penyuluh($penyuluh) {
        $this->datatables->select('survei.id,keluarga.kepala_keluarga,keluarga.penyuluh_id');
        $this->datatables->from('survei');
        $this->datatables->where('keluarga.penyuluh_id',$penyuluh);
        //add this line for join
        $this->datatables->join('keluarga', 'survei.keluarga_id = keluarga.id');
        $this->datatables->add_column('action', anchor(site_url('survei/read/$1'),'Detail')." | ".anchor(site_url('survei/update/$1'),'Perbarui')." | ".anchor(site_url('survei/delete/$1'),'Hapus','onclick="javasciprt: return confirm(\'Apakah anda yakin ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('survei.id,sayur,buah,umbi,hewani,kacang,keluarga_id,kepala_keluarga');
        $this->db->join('keluarga','keluarga.id = survei.keluarga_id');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('sayur', $q);
        $this->db->or_like('buah', $q);
        $this->db->or_like('umbi', $q);
        $this->db->or_like('hewani', $q);
        $this->db->or_like('kacang', $q);
        $this->db->or_like('keluarga_id', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('sayur', $q);
	$this->db->or_like('buah', $q);
	$this->db->or_like('umbi', $q);
	$this->db->or_like('hewani', $q);
	$this->db->or_like('kacang', $q);
	$this->db->or_like('keluarga_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Survei_model.php */
/* Location: ./application/models/Survei_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-28 16:17:59 */
/* http://harviacode.com */