<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_keluarga_model extends CI_Model
{

    public $table = 'user_keluarga';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($id) {
        $this->datatables->select('user_keluarga.id,user_id,user.nama,user.nik,TIMESTAMPDIFF(YEAR, user.tgl_lahir, CURDATE()) AS age,keluarga_id,hubungan,user.pendidikan,user.pekerjaan,user.jk,user.agama');
        $this->datatables->from('user_keluarga');
        $this->datatables->where('keluarga_id',$id);
        //add this line for join
        $this->datatables->join('user', 'user_keluarga.user_id = user.id');
        $this->datatables->add_column('action', anchor(site_url('user_keluarga/delete/$1/'.$id),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('user_id', $q);
	$this->db->or_like('keluarga_id', $q);
	$this->db->or_like('hubungan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('user_id', $q);
	$this->db->or_like('keluarga_id', $q);
	$this->db->or_like('hubungan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file User_keluarga_model.php */
/* Location: ./application/models/User_keluarga_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-27 07:43:00 */
/* http://harviacode.com */